//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace TechStore
{

    /// <summary>
    /// Klasa Kompatibilnost.
    /// </summary>
    public partial class Kompatibilnost
    {
        public int Komponenta1 { get; set; }
        public int Komponenta2 { get; set; }
        public bool Kompatibilni { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Artikl Artikl1 { get; set; }


        /// <summary>
        /// Statièka metoda koja kao argument prima novu kompatibilnost.
        /// Metoda dodaje novu kompatibilnost u bazu podataka.
        /// </summary>
        /// <param name="novaKompatibilnost"></param>
        public static void DodajKompatibilnost(Kompatibilnost novaKompatibilnost) {
            using (var db = new TechStoreEntities())
            {
                db.Kompatibilnost.Attach(novaKompatibilnost);
                db.Kompatibilnost.Add(novaKompatibilnost);
                db.SaveChanges();
            }
        }

        /// <summary>
        /// Statièka metoda koja kao argument prima kompatibilnost koja se želi obrisati.
        /// Metoda briše odabranu kompatibilnost iz baze podataka.
        /// </summary>
        /// <param name="kompatibilnostZaBrisanje"></param>
        public static void ObrisiKompatibilnost(Kompatibilnost kompatibilnostZaBrisanje) {
            using (var db= new TechStoreEntities())
            {
                db.Kompatibilnost.Attach(kompatibilnostZaBrisanje);
                db.Kompatibilnost.Remove(kompatibilnostZaBrisanje);
                db.SaveChanges();
            }
        }

       /// <summary>
       /// Statièka metoda koja kao argument prima upit koji se izvršava.
       /// Metoda izvršava proslijeðeni upit te dohvaæa sve kompatibilnosti
       /// koje zadovoljavaju upit te ih sprema u listu kompatibilnosti.
       /// Metoda vraæa listu kompatibilnosti.
       /// </summary>
       /// <param name="upit"></param>
       /// <returns></returns>
        public static List<Kompatibilnost> DohvatiKompatibilnosti(string upit) {
            List<Kompatibilnost> listaKompatibilnosti = null;
            using (var db= new TechStoreEntities())
            {
                listaKompatibilnosti = db.Kompatibilnost.SqlQuery(upit).ToList();
            }
            return listaKompatibilnosti;
        }
    }
}
