//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanjeDokumenta
    {
        public int Dokument_ID { get; set; }
        public int VrstaStanja_ID { get; set; }
        public int Zaposlenik_ID { get; set; }
        public byte[] Datum_promjene { get; set; }
        public string Napomena { get; set; }
    
        public virtual Dokument Dokument { get; set; }
        public virtual VrsteStanja VrsteStanja { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }

        public static void DodajStanjeDokumenta(StanjeDokumenta stanjeDokumenta) {
            using (var db= new TechStoreEntities())
            {
                db.StanjeDokumenta.Attach(stanjeDokumenta);
                db.StanjeDokumenta.Add(stanjeDokumenta);
                db.SaveChanges();
            }
        }
    }
}
