//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;

    public partial class StavkaDokumenta
    {
        public int Artikl_ID { get; set; }
        public int Dokument_ID { get; set; }
        public int Kolicina { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Dokument Dokument { get; set; }

        public static void DodajStavkuDokumenta(StavkaDokumenta stavkaDokumenta)
        {
            using (var db= new TechStoreEntities())
            {
                db.StavkaDokumenta.Attach(stavkaDokumenta);
                db.StavkaDokumenta.Add(stavkaDokumenta);
                db.SaveChanges();
            }
        }

        public static BindingList<StavkaDokumenta> DohvatiStavkeDokumenta(Dokument dokument)
        {
            BindingList<StavkaDokumenta> listaStavaka = null;
            using (var db= new TechStoreEntities())
            {
                db.Dokument.Attach(dokument);
                listaStavaka = new BindingList<StavkaDokumenta>(dokument.StavkaDokumenta.ToList());
            }
            return listaStavaka;
        }
    }
}
