//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechStoreEntities : DbContext
    {
        public TechStoreEntities()
            : base("name=TechStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikl> Artikl { get; set; }
        public virtual DbSet<Dokument> Dokument { get; set; }
        public virtual DbSet<Dostupnost> Dostupnost { get; set; }
        public virtual DbSet<Kompatibilnost> Kompatibilnost { get; set; }
        public virtual DbSet<Poslovnica> Poslovnica { get; set; }
        public virtual DbSet<StanjeDokumenta> StanjeDokumenta { get; set; }
        public virtual DbSet<StavkaDokumenta> StavkaDokumenta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipZaposlenika> TipZaposlenika { get; set; }
        public virtual DbSet<VrstaArtikla> VrstaArtikla { get; set; }
        public virtual DbSet<VrstaDokumenta> VrstaDokumenta { get; set; }
        public virtual DbSet<VrsteStanja> VrsteStanja { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
