//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;

    public partial class VrstaDokumenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VrstaDokumenta()
        {
            this.Dokument = new HashSet<Dokument>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokument { get; set; }


        /// <summary>
        /// Statièka metoda koja vraæa listu svih vrsta dokumenata
        /// iz baze podataka.
        /// </summary>
        /// <returns></returns>
        public static BindingList<VrstaDokumenta> DohvatiVrsteDokumenta() {
            BindingList<VrstaDokumenta> listaVrstaArtikala = null;
            using (var db= new TechStoreEntities())
            {
                listaVrstaArtikala = new BindingList<VrstaDokumenta>(db.VrstaDokumenta.ToList());
            }
            return listaVrstaArtikala;
        }
    }
}
